spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/floci_demo
    username: floci
    password: floci

app:
  demo:
    region: us-east-1
    aws:
      access-key: test
      secret-key: test
      endpoint-url: http://localhost:4566
    s3:
      bucket: floci-demo-bucket
      key: payloads/payloads.json
    sqs:
      queue-name: floci-demo-queue
    sns:
      topic-name: floci-demo-topic
      subscription-queue-name: floci-demo-sns-subscription-queue
    lambda:
      function-name: floci-demo-enrichment
    ssm:
      batch-size-parameter: /floci-demo/batchsize
      use-lambda-parameter: /floci-demo/useLambda
    defaults:
      batch-size: 3
      use-lambda: false
    consumer:
      enabled: true
      poll-delay-ms: 3000
      max-messages: 10
